# Generated by Django 5.1.7 on 2025-04-02 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooklibApp', '0004_alter_book_genres_alter_book_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='marked_by',
            field=models.ManyToManyField(blank=True, related_name='marked_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
