# Generated by Django 5.1.7 on 2025-04-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooklibApp', '0006_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
